print("script1")
# JSON 属性赋值示例，以 "."开头的代表转换的JSON 的根
.group[4]=1
.ext=123*123

# 变量赋值 变量 不以"." 开头
# 变量与性属的区别 ：属性会在JSON转换结果里出现，而变量只是中间过程，不会在JSON中体现
var1 = 2
var2 = '2023'

# 和字符串相加后，变量会变成字符串
var3 = var1+var2

# 四则运算
var4 =var1*.ext*(1+13/2)

# 把变量的值赋给 属性
.fromvar= var4
.fromvar=.fromvar/3
# 移动属性 ，把.addr.contry， 提到根下
move(.addr.contry,.contry)

# 分枝
if (.ext==123) {.abc=true}
if (var2=='2023') {.att5='203333'}

# 遍历
each(.group){.=.+9999}

# 移除属性
del(.age)

# 综合用法

tmp=0
a='eric'
each(.persons){ 
    tmp = tmp+1
   .name=.name+tmp 
   .age= tmp%3*10+tmp*2
   if (tmp%3 ==0) {
    .a[0]=tmp
   }
}



# 综合示例2 求0-10 之前的奇数
# 初始化一个数组
temp1[10]=1
at=0
each(temp1){
    .=at
    if (at%2==0) { del(.)}
    at=at+1
}
.odd=temp1
a.name="eric"
a.age=13
# 把自身往下移一个层
.=a
//move(.,.data)

