bt=timestamp
http.config.connectTimeout=1000
http.config.readTimeout=1000
#http.config.cache=false
#resp=httpget("https://kaifa.baidu.com/rest/v1/cards?wd=http")
.httpcode=resp.code
.summary=resp.data.data.summary
if (resp.code == 200) {
    .successed=true
}else if(a==1){
    .b=1
}else{
    j=l
}
.test = resp.code == 200 #123456
.time=now
.timestamp=timestamp
et=timestamp
.tooks=et-bt
each(.names){ 
    tmp=tmp+1
    if(. ==null ){
        .=nb+tmp
    }
}

if (int(i-1)==1){
    c=p
}

a  = - 1

b =3+2